apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-otel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-otel
  template:
    metadata:
      labels:
        app: fastapi-otel
    spec:
      containers:
        - name: fastapi
          image: okeyobia/fastapi-otel:f55117a739d2dd0b14cb6060349672f777bcc14d
          ports:
            - containerPort: 8000
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4318