---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dynatrace-otlp
  namespace: fastapi-otel
spec:
  encryptedData:
    API_TOKEN: AgBRB/ePpq7Lt304NpBDnmljGA1L3HYGXg4VRI+mAZq2aKazwWbDO6MXUw8kn5dIcX3fgYz2fY5mTXh+XfkG3HuOeLBptRjEegQw5UT28smLRIGipbJavZKJmbMCvd1BnNRrDalnfPlrpotzD7HCcncYKYDS+l9D4oEV2Sq6nPuK5/unghMMiCmm6TbvrZhplp2tKBeOH9PcwNGo0b0Xpy+aN/9AxbzczNWluQD0lhmfOE0r7sZVrB2LkITfiYdb2IAgtKGxoljTph2xG80P3rSwQDCZ+RyR/qm7y0h3MTe4Pgifw/+xlH/OSNM9RRxcYKJtoGk/xu+7Zeyh3QRjOZ5ULsUbDi2tRsmu2PosCsDOWkS9A38At6bMN9No2y3ztxjy/tpcoOBoVL4Fg+h0jqo+JmLkteArU+Yix1dtQGW2CS/xFATXtDk18104dIWmFsXKzi5GR+3SQp1nCOa7mkxhlH7bp+ARvoI4d9Tn7mhuRjoI7pm/4MpRfMP9rLhqehzcu7T12bgVSEwFLafMZkn9MwluWsYeE16+8aLrBVBDlsvyHVbI2JnxjLUaXA1B5AUiRdZMOi2Fws4LZavcsvmqukhYRPcT6Y7qxwYhMIFdqlLO7pkWpgiYiYZ/tkt7hWlh1yFNqyogQ4oNjDwQ2/xhtzb1mBhc0gKTzY9G3Qiksen5j0pg2ipc0fX3/I12fgVZFono84dy2Mdd5SUboX/d5gcQAPNB7v5DhWjHTrGwbwGK0dEmEj1v3T51iMq2oqppu1KMv1xXQaKb9ntCLw9NZpFcPcXD5MJt70/ilu2tSkVwCaBykM+Hed9iaNmKlUk=
    tenantUrl: AgA7NhvfLmsOCteqjn9IsdLLw1rRpIKJI4yxS1OWri/ReSlOOu9NxbR5lO8aWoJEiPdQ5ETLhMXcJYCfwtFZ5JK0/ftryth6HLXZekeJXtnR33mzYeiIzhsvD3+WKzCPETKiukAjOtPVz7v5wjCMHq5MfL5cURIuDw8O1PqKbqCcJIxgpqcnCOVjsNlJe3sypqVgs4INib39zj+pkS24kxJgtIrh/JjDyIX5zjXyPTWy2id8uSRDjIxJSnT8SBGh0qbaWFCgcvR2U3jqt6qRGnqam/boe/rEPsJX16pyJzeAe/K0/K8k1QQiv/AbH9BYYJWnSSSpZVvOrXXlKKPFuxsL2g1I+BjBNNVi/GYc8vWeA55QCQ1aFQd5V1QsMex4ib1CWx3QH6sJfjPg2Y9E3ZF8DPpWi4k8xNUf0uKlPZFs8+wd16ptdKYv6MkL1DonK76nfkphc25aY+zb09or0aZfOenAaoTwDhUJ+tuG64+fTXXkf29M6NGNIzhzqbiN0GDjxnidYE0DBrXYm1uV2xW7IClik+CJ0PmzU8DN0wVP5i4TUQKn5r3LMRkknGJPBWrIZAYOZ/WSTeVOtW/Hsjjw5xrDXv6XDh6MbZUvsS6jbbN+nXYDGlMFHITU/ST/5sBzpiusrQv+nCybzwTs2KhuIF3TRkHPujvQFNOL8NAl5T+gtUfJ0GdepDVUla0+1HFXXy6tOFUBeSY40JX7A3mpX7E2dh26+I50RFqUq7M5Bl+HddydX8Nx8BN5w/Pmug==
  template:
    metadata:
      name: dynatrace-otlp
      namespace: fastapi-otel
    type: Opaque
