apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
          grpc:

    exporters:
      otlphttp/dynatrace:
        endpoint: "https://YOUR_ENV.live.dynatrace.com/api/v2/otlp"
        headers:
          Authorization: "Api-Token YOUR_API_TOKEN"

    processors:
      batch:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/dynatrace]